/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardSignalsIndexRouteImport } from './routes/dashboard/signals/index'
import { Route as DashboardRecordingsIndexRouteImport } from './routes/dashboard/recordings/index'
import { Route as DashboardChatIndexRouteImport } from './routes/dashboard/chat/index'
import { Route as DashboardSignalsSignalIdRouteImport } from './routes/dashboard/signals/$signalId'
import { Route as DashboardRecordingsRecordingIdRouteImport } from './routes/dashboard/recordings/$recordingId'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSignalsIndexRoute = DashboardSignalsIndexRouteImport.update({
  id: '/signals/',
  path: '/signals/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRecordingsIndexRoute =
  DashboardRecordingsIndexRouteImport.update({
    id: '/recordings/',
    path: '/recordings/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardChatIndexRoute = DashboardChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSignalsSignalIdRoute =
  DashboardSignalsSignalIdRouteImport.update({
    id: '/signals/$signalId',
    path: '/signals/$signalId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardRecordingsRecordingIdRoute =
  DashboardRecordingsRecordingIdRouteImport.update({
    id: '/recordings/$recordingId',
    path: '/recordings/$recordingId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/recordings/$recordingId': typeof DashboardRecordingsRecordingIdRoute
  '/dashboard/signals/$signalId': typeof DashboardSignalsSignalIdRoute
  '/dashboard/chat': typeof DashboardChatIndexRoute
  '/dashboard/recordings': typeof DashboardRecordingsIndexRoute
  '/dashboard/signals': typeof DashboardSignalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/recordings/$recordingId': typeof DashboardRecordingsRecordingIdRoute
  '/dashboard/signals/$signalId': typeof DashboardSignalsSignalIdRoute
  '/dashboard/chat': typeof DashboardChatIndexRoute
  '/dashboard/recordings': typeof DashboardRecordingsIndexRoute
  '/dashboard/signals': typeof DashboardSignalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/recordings/$recordingId': typeof DashboardRecordingsRecordingIdRoute
  '/dashboard/signals/$signalId': typeof DashboardSignalsSignalIdRoute
  '/dashboard/chat/': typeof DashboardChatIndexRoute
  '/dashboard/recordings/': typeof DashboardRecordingsIndexRoute
  '/dashboard/signals/': typeof DashboardSignalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/recordings/$recordingId'
    | '/dashboard/signals/$signalId'
    | '/dashboard/chat'
    | '/dashboard/recordings'
    | '/dashboard/signals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/recordings/$recordingId'
    | '/dashboard/signals/$signalId'
    | '/dashboard/chat'
    | '/dashboard/recordings'
    | '/dashboard/signals'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/recordings/$recordingId'
    | '/dashboard/signals/$signalId'
    | '/dashboard/chat/'
    | '/dashboard/recordings/'
    | '/dashboard/signals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/signals/': {
      id: '/dashboard/signals/'
      path: '/signals'
      fullPath: '/dashboard/signals'
      preLoaderRoute: typeof DashboardSignalsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/recordings/': {
      id: '/dashboard/recordings/'
      path: '/recordings'
      fullPath: '/dashboard/recordings'
      preLoaderRoute: typeof DashboardRecordingsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/chat/': {
      id: '/dashboard/chat/'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/signals/$signalId': {
      id: '/dashboard/signals/$signalId'
      path: '/signals/$signalId'
      fullPath: '/dashboard/signals/$signalId'
      preLoaderRoute: typeof DashboardSignalsSignalIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/recordings/$recordingId': {
      id: '/dashboard/recordings/$recordingId'
      path: '/recordings/$recordingId'
      fullPath: '/dashboard/recordings/$recordingId'
      preLoaderRoute: typeof DashboardRecordingsRecordingIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardRecordingsRecordingIdRoute: typeof DashboardRecordingsRecordingIdRoute
  DashboardSignalsSignalIdRoute: typeof DashboardSignalsSignalIdRoute
  DashboardChatIndexRoute: typeof DashboardChatIndexRoute
  DashboardRecordingsIndexRoute: typeof DashboardRecordingsIndexRoute
  DashboardSignalsIndexRoute: typeof DashboardSignalsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardRecordingsRecordingIdRoute: DashboardRecordingsRecordingIdRoute,
  DashboardSignalsSignalIdRoute: DashboardSignalsSignalIdRoute,
  DashboardChatIndexRoute: DashboardChatIndexRoute,
  DashboardRecordingsIndexRoute: DashboardRecordingsIndexRoute,
  DashboardSignalsIndexRoute: DashboardSignalsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
