#include "mic.h"
#include "FreeRTOSConfig.h"
#include "driver/i2s_pdm.h"
#include "driver/i2s_std.h"
#include "esp_log.h"
#include "freertos/projdefs.h"
#include "portmacro.h"

static const char *TAG = "zanin-mic";

Microphone::Microphone(gpio_num_t blck, gpio_num_t dio, gpio_num_t lrcl)
    : blck(blck), dio(dio), lrcl(lrcl) {
  /* Get the default channel configuration by helper macro.
   * This helper macro is defined in `i2s_common.h` and shared by all the I2S
   * communication modes. It can help to specify the I2S role and port ID */
  i2s_chan_config_t chan_cfg =
      I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_AUTO, I2S_ROLE_MASTER);

  /* Allocate a new RX channel and get the handle of this channel */
  i2s_new_channel(&chan_cfg, NULL, &(this->rx_handle));
  ESP_LOGI(TAG, "Created new i2s channel");

  /* Setting the configurations, the slot configuration and clock configuration
   * can be generated by the macros These two helper macros are defined in
   * `i2s_std.h` which can only be used in STD mode. They can help to specify
   * the slot and clock configurations for initialization or updating */
  i2s_std_config_t std_cfg = {
      .clk_cfg = I2S_STD_CLK_DEFAULT_CONFIG(16000), // 16 kHz sample rate
      .slot_cfg = I2S_STD_PHILIPS_SLOT_DEFAULT_CONFIG(
          I2S_DATA_BIT_WIDTH_32BIT,
          I2S_SLOT_MODE_STEREO // mic uses LEFT slot
          ),
      .gpio_cfg =
          {
              .mclk = I2S_GPIO_UNUSED,
              .bclk = blck,
              .ws = lrcl,
              .dout = I2S_GPIO_UNUSED,
              .din = dio,
              .invert_flags =
                  {
                      .mclk_inv = false,
                      .bclk_inv = false,
                      .ws_inv = false,
                  },
          },
  };
  /* Initialize the channel */
  i2s_channel_init_std_mode(this->rx_handle, &std_cfg);
  ESP_LOGI(TAG, "Initialized i2s channel");
}

void Microphone::start() {
  i2s_channel_enable(this->rx_handle);
  ESP_LOGI(TAG, "Enabled i2s channel");
}

esp_err_t Microphone::read(void *buffer, size_t bytes_to_read,
                           size_t *bytes_read, uint32_t timeout_ms) {
  TickType_t ticks = pdMS_TO_TICKS(timeout_ms);
  return i2s_channel_read(this->rx_handle, buffer, bytes_to_read, bytes_read,
                          ticks);
}

void Microphone::stop() {
  /* Have to stop the channel before deleting it */
  i2s_channel_disable(this->rx_handle);
  /* If the handle is not needed any more, delete it to release the channel
   * resources */
  i2s_del_channel(this->rx_handle);
  ESP_LOGI(TAG, "Disabled i2s channel");
}
